name: 'Registry Login'
description: 'Login to Docker Hub, GitHub Container Registry, and Quay.io'
inputs:
  docker_hub_username:
    description: 'Docker Hub username'
    required: true
  docker_hub_token:
    description: 'Docker Hub token'
    required: true
  github_token:
    description: 'GitHub token'
    required: true
  quay_username:
    description: 'Quay.io username'
    required: true
  quay_robot_token:
    description: 'Quay.io robot token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_hub_username }}
        password: ${{ inputs.docker_hub_token }}
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github_token }}
    
    - name: Login to Quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ inputs.quay_username }}
        password: ${{ inputs.quay_robot_token }}